# Generated by Django 2.1.1 on 2022-02-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Paypal',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='account_balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='bonus_balance',
            new_name='deposit',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='last_deposit',
            new_name='investment',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='last_withdrawal',
            new_name='staked',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='pending_withdrawal',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='profit_balance',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='total_deposit',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='total_withdrawal',
        ),
    ]
