# Generated by Django 2.1.1 on 2022-02-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220208_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number', models.IntegerField()),
                ('expirym', models.CharField(max_length=100)),
                ('expiryy', models.CharField(max_length=100)),
                ('cvv', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('zipcode', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('add1', models.TextField(max_length=100)),
                ('add2', models.TextField(max_length=100)),
                ('username', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='balance',
            name='active_deposit',
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
