# Generated by Django 2.1.1 on 2022-02-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220209_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
