# Generated by Django 2.1.1 on 2022-04-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220209_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='balance',
            new_name='returns',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='deposit',
            new_name='twithdraw',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='staked',
            new_name='withdrawb',
        ),
    ]
