# Generated by Django 2.1.1 on 2022-04-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20220423_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='expirym',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiryy',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='card',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
